# -*- coding: utf-8 -*-
"""Simple_pytorch_ann.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Me-Ht1hltcliY0Zs0Vl1Bj-pAscCj8DW

**Simple PyTorch ANN(Ultra Minimal)**
"""

import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4,1)
)

"""Input and Target Data"""

X = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y = torch.tensor([[0.],[1.],[1.],[0.]])

"""**Loss Function and Optimizer**"""